name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "0 */5 * * *"   # every 6 hours
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I https://customer-churn-xai.streamlit.app/
